Using pandas answer at least 4 of the 6 questions you wrote in the first part of your project. Include code to generate at least one data visualization or summary table as output, and 2-3 sentences of written interpretation of what you found.

You are expected to use a variety of pandas operations in your notebook. You can use...

groupby() to aggregate data across a categorical column.

pivot_table() to summarize a relationship between two categorical variables.

boolean filtering to isolate a subset of the data to answer a specific question.

Your notebook should be readable from top to bottom, as if it was a short report. Use markdown cells to format your report to:

title each section with the question you're investigating
your interpretation after each output

In [ ]:
import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv('../data/raw/shopping.csv')

df.head()

df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3510 non-null   float64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Purchase Amount (USD)   3900 non-null   float64
 5   Location                3510 non-null   str
 6   Size                    3900 non-null   str
 7   Color                   3900 non-null   str
 8   Season                  3900 non-null   str
 9   Review Rating           1431 non-null   float64
 10  Shipping Type           3900 non-null   str
 11  Promo Code Used         3900 non-null   str
 12  Previous Purchases      3900 non-null   int64
 13  Payment Method          3900 non-null   str
 14  Frequency of Purchases  1560 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 457.2 KB

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3510.000000,3900.000000,1431.000000,3900.000000
mean,1950.500000,34.256695,38.708329,3.904962,5.841538
std,1125.977353,10.616340,11.504923,1.105952,5.843695
min,1.000000,18.000000,11.392520,1.000000,0.000000
25%,975.750000,26.000000,29.332617,4.000000,1.000000
50%,1950.500000,33.000000,36.953004,4.000000,4.000000
75%,2925.250000,41.000000,48.739596,5.000000,9.000000
max,3900.000000,75.000000,69.567481,5.000000,20.000000

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Shipping Type,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,3475,NaN,Male,Jacket,30.904467,Maine,M,Burnt orange,Fall,4.0,Standard,No,0,Credit Card,NaN
1,3698,21.0,Female,Backpack,31.588259,NaN,L,Turquoise,Winter,2.0,Express,No,1,Credit Card,Monthly
2,2756,31.0,Male,Leggings,24.231704,Nevada,M,Terra cotta,Winter,4.0,Standard,No,0,Credit Card,NaN
3,3340,NaN,Male,Pajamas,33.918834,Nebraska,M,Black,Winter,NaN,Standard,No,2,Credit Card,Bi-Weekly
4,3391,38.0,Male,Sunglasses,36.545487,Oregon,S,Aubergine,Summer,NaN,Standard,No,0,Credit Card,NaN

In [13]:
df.pivot_table(values="Purchase Amount (USD)", index="Location", columns="Gender", aggfunc="mean")

Gender             Female       Male  Non-binary
Location
Alabama         37.078603  36.084544         NaN
Alaska          35.369486  37.015142         NaN
Arizona         36.266031  36.896224   36.876751
Arkansas        41.494105  38.193216         NaN
California      38.161198  38.567013   33.106153
Colorado        39.589902  34.897295         NaN
Connecticut     35.988479  35.129898         NaN
Delaware        39.173337  38.671335   35.811128
Florida         40.820284  39.890744         NaN
Georgia         37.835086  38.694525         NaN
Hawaii          42.640052  40.657137         NaN
Idaho           40.141382  38.698120   28.379849
Illinois        37.762948  36.936073         NaN
Indiana         42.995251  43.861954         NaN
Iowa            41.980723  41.847215   29.202617
Kansas          34.667430  35.127604         NaN
Kentucky        39.915698  35.359450   49.139632
Louisiana       38.085553  39.703345   29.067419
Maine           38.628540  38.760732   24.288400
Maryland        39.508788  39.685734         NaN
Massachusetts   38.996479  42.332443         NaN
Michigan        36.741381  39.111024         NaN
Minnesota       37.125494  38.091769   50.061226
Mississippi     39.334826  36.055375   57.516059
Missouri        40.751322  40.950864         NaN
Montana         41.613393  36.146675   58.380665
Nebraska        38.429770  41.463528         NaN
Nevada          38.933311  39.995215         NaN
New Hampshire   39.219401  39.556315         NaN
New Jersey      39.821737  36.918718         NaN
New Mexico      39.362757  39.913030   22.447164
New York        38.679831  40.433352         NaN
North Carolina  41.502406  38.594343   40.192618
North Dakota    41.031635  37.324164   42.702367
Ohio            38.760226  39.825733   28.399281
Oklahoma        38.025164  37.816715   25.081016
Oregon          40.930178  38.952989         NaN
Pennsylvania    39.409710  36.777839   46.092374
Rhode Island    38.004470  38.663944         NaN
South Carolina  39.707795  41.565828   24.998480
South Dakota    37.494877  37.801578         NaN
Tennessee       37.212958  37.882801   58.314316
Texas           39.777360  37.487195   34.737877
Utah            37.497831  40.477406   37.662222
Vermont         36.444460  38.435348         NaN
Virginia        37.072909  38.498086         NaN
Washington      35.728880  41.452185   44.794063
West Virginia   40.393752  39.679752   42.730933
Wisconsin       40.502391  38.753045   22.842739
Wyoming         39.353041  37.145614         NaN

In [ ]:
def f(col): 
    return col.max() - col.min()

f = lambda col: col.max() - col.min()

In [ ]:
df.groupby("Location")[["Review Rating", "Purchase Amount (USD)"]].agg(lambda col: col.max() - col.min())

                Review Rating  Purchase Amount (USD)
Location
Alabama                   4.0              42.899896
Alaska                    4.0              48.859351
Arizona                   4.0              40.179193
Arkansas                  3.0              41.803491
California                3.0              43.316409
Colorado                  4.0              46.488488
Connecticut               4.0              45.622360
Delaware                  3.0              50.313108
Florida                   4.0              40.044420
Georgia                   3.0              40.965594
Hawaii                    1.0              45.015649
Idaho                     3.0              52.324291
Illinois                  3.0              43.283771
Indiana                   3.0              40.268702
Iowa                      4.0              45.435539
Kansas                    4.0              38.681417
Kentucky                  3.0              36.681227
Louisiana                 4.0              43.941942
Maine                     4.0              40.385544
Maryland                  3.0              44.252337
Massachusetts             3.0              50.414799
Michigan                  3.0              37.738828
Minnesota                 4.0              41.382899
Mississippi               3.0              50.517703
Missouri                  3.0              40.319944
Montana                   4.0              51.592891
Nebraska                  4.0              40.889497
Nevada                    3.0              50.782517
New Hampshire             3.0              43.024792
New Jersey                4.0              48.451458
New Mexico                4.0              41.302078
New York                  4.0              45.605143
North Carolina            4.0              54.117815
North Dakota              4.0              39.833369
Ohio                      4.0              47.901726
Oklahoma                  1.0              39.698990
Oregon                    3.0              38.359677
Pennsylvania              3.0              48.295792
Rhode Island              4.0              44.032489
South Carolina            4.0              37.794727
South Dakota              2.0              46.018118
Tennessee                 3.0              39.313320
Texas                     3.0              43.353926
Utah                      3.0              45.474291
Vermont                   4.0              52.232428
Virginia                  4.0              40.187499
Washington                3.0              40.744761
West Virginia             4.0              47.136434
Wisconsin                 4.0              44.822485
Wyoming                   1.0              47.385693

In [ ]:
import pandas as pd

shopping_data = pd.read_csv("data/processed/shopping_cleaned.csv")

In [9]:
df.groupby("Gender")["Purchase Amount (USD)"].sum()

Gender
Female        73620.710082
Male          76032.285805
Non-binary     1309.485399
Name: Purchase Amount (USD), dtype: float64

In [56]:
# What gender buys the most by total number of orders?
df.groupby("Gender")["Frequency of Purchases"].count()

Gender
Female        746
Male          799
Non-binary     15
Name: Frequency of Purchases, dtype: int64

In [53]:
# On what items do the customers spend the most?
df["Item Purchased"].value_counts()

Item Purchased
Shorts           314
Sunglasses       312
Running Shoes    309
Dress            294
Handbag          267
T-shirt          262
Sweater          231
Leggings         228
Backpack         225
Gloves           217
Pajamas          212
Socks            211
Hoodie           202
Scarf            196
Jacket           166
Boots            166
Jeans             54
Belt              34
Name: count, dtype: int64

In [44]:
# What item has the best review?
df.groupby("Item Purchased")["Review Rating"].value_counts()

Item Purchased  Review Rating
Backpack        4.0              42
                5.0              29
                2.0              22
                1.0               2
Belt            4.0              10
                                 ..
T-shirt         4.0              53
                5.0              31
                2.0              16
                1.0               3
                3.0               1
Name: count, Length: 71, dtype: int64

In [41]:
# What size is purchased the most? 
df["Size"].value_counts()

Size
M     1755
L     1053
S      663
XL     429
Name: count, dtype: int64